export const cartItems = [{
        image: "/images/image.jpg",
        name: "iPhone 4s",
        price: 120,
        size: "5 inch",
        ram: "4GB",
        storage: "32GB",
        id: 1,
        singleAmount: 1,
    },
    {
        image: "/images/5s.jpg",
        name: "iPhone 5s",
        price: 180,
        size: "7 inch",
        ram: "6GB",
        storage: "64GB",
        id: 2,
        singleAmount: 1,
    },
    {
        image: "/images/6s.jpg",
        name: "iPhone 6s",
        price: 240,
        size: "8 inch",
        ram: "8GB",
        storage: "128GB",
        id: 3,
        singleAmount: 1,
    },
];